local T = require("t")
local Fakes = require("fakes")

local function link(server)
    local Hardcover = require("hardcover")
    local device = assert(Hardcover:startLink())
    local result, err
    for _ = 1, 10 do
        result, err = Hardcover:poll(device.device_code)
        if result ~= "pending" and result ~= "slow_down" then break end
    end
    return result, err, device
end

T.describe("hardcover availability", function()
    T.it("the shipped client id makes it available", function()
        T.ok(require("hardcover"):isAvailable())
    end)
    T.it("a build without a client id is unavailable and refuses to start", function()
        local Hardcover = require("hardcover")
        Hardcover.CLIENT_ID = ""
        T.ok(not Hardcover:isAvailable())
        local device, err = Hardcover:startLink()
        T.eq(device, nil)
        T.eq(err, "no client id")
    end)
    T.it("nothing is linked on a fresh install", function()
        T.ok(not require("hardcover"):isLinked())
    end)
end)

T.describe("hardcover device sign-in", function()
    T.it("pending polls, then a stored token pair", function()
        local server = Fakes.hardcover({ pending = 2 })
        T.eq(link(server), "linked")
        T.eq(server.polls, 3)
        local account = require("settings"):get("hardcover")
        T.eq(account.access_token, "hc_at_1")
        T.eq(account.refresh_token, "hc_rt_1")
        T.ok(account.expires_at > os.time() + 600000, "expiry from expires_in")
    end)
    T.it("slow_down is reported so the screen can back off", function()
        Fakes.hardcover({ slow_down = true })
        local Hardcover = require("hardcover")
        local device = Hardcover:startLink()
        T.eq(Hardcover:poll(device.device_code), "slow_down")
        T.eq(Hardcover:poll(device.device_code), "linked")
    end)
    T.it("a declined request fails with access_denied and stores nothing", function()
        Fakes.hardcover({ deny = true })
        local result, err = link()
        T.eq(result, "failed")
        T.eq(err, "access_denied")
        T.ok(not require("hardcover"):isLinked())
    end)
    T.it("a dropped connection while polling counts as pending, not failure", function()
        local server = Fakes.hardcover({ pending = 5 })
        local Hardcover = require("hardcover")
        local device = Hardcover:startLink()
        server.online = false
        T.eq(Hardcover:poll(device.device_code), "pending")
    end)
    T.it("starting offline reports an error rather than throwing", function()
        local server = Fakes.hardcover()
        server.online = false
        local device, err = require("hardcover"):startLink()
        T.eq(device, nil)
        T.ok(err, "an error message")
    end)
    T.it("the username is fetched and remembered; `me` as array or object", function()
        local server = Fakes.hardcover()
        link(server)
        T.eq(require("hardcover"):fetchMe(), "reader")
        T.eq(require("hardcover"):username(), "reader")
        server.me = { id = 8, username = "solo" }
        T.eq(require("hardcover"):fetchMe(), "solo")
    end)
end)

T.describe("hardcover tokens", function()
    T.it("an expired access token is refreshed before the query", function()
        local server = Fakes.hardcover()
        link(server)
        local Settings = require("settings")
        local a = Settings:get("hardcover"); a.expires_at = os.time() - 5; Settings:set("hardcover", a)
        T.ok(require("hardcover"):query("{ me { id } }"), "query succeeds")
        T.eq(Settings:get("hardcover").refresh_token, "hc_rt_2", "rotated pair stored")
        T.ok(not server.replayed)
    end)
    T.it("a rejected token is refreshed once and retried once", function()
        local server = Fakes.hardcover()
        link(server)
        local Settings = require("settings")
        local a = Settings:get("hardcover"); a.access_token = "stale"; Settings:set("hardcover", a)
        T.ok(require("hardcover"):query("{ me { id } }"))
        local graphql = 0
        for _, call in ipairs(server.log) do if call.path == "/v1/graphql" then graphql = graphql + 1 end end
        T.eq(graphql, 2)
    end)
    T.it("persistent 401s do not loop", function()
        local server = Fakes.hardcover()
        link(server)
        local Hardcover = require("hardcover")
        local post = Hardcover.post
        local graphql = 0
        Hardcover.post = function(self, path, ...)
            if path == "/v1/graphql" then graphql = graphql + 1; return 401, {} end
            return post(self, path, ...)
        end
        T.eq(Hardcover:query("{ me { id } }"), nil)
        T.ok(graphql <= 2, "at most one retry, got " .. graphql)
    end)
    T.it("many refreshes in a row never reuse a spent refresh token", function()
        local server = Fakes.hardcover()
        link(server)
        local Settings = require("settings")
        for _ = 1, 20 do
            local a = Settings:get("hardcover"); a.expires_at = 0; Settings:set("hardcover", a)
            -- reload from disk each time, like a restart between refreshes
            package.loaded["settings"], package.loaded["hardcover"] = nil, nil
            Settings = require("settings")
            Fakes.hardcover_rebind(server)
            T.ok(require("hardcover"):query("{ me { id } }"))
        end
        T.ok(not server.replayed, "no replay")
        T.eq(Settings:get("hardcover").refresh_token, "hc_rt_21")
    end)
    T.it("a revoked chain forgets the account so the user can link again", function()
        local server = Fakes.hardcover()
        link(server)
        server.refresh = nil  -- revoked on Hardcover's side
        local Settings = require("settings")
        local a = Settings:get("hardcover"); a.expires_at = 0; Settings:set("hardcover", a)
        T.eq(require("hardcover"):query("{ me { id } }"), nil)
        T.ok(not require("hardcover"):isLinked())
    end)
    T.it("an offline refresh keeps the account for later", function()
        local server = Fakes.hardcover()
        link(server)
        server.online = false
        local Settings = require("settings")
        local a = Settings:get("hardcover"); a.expires_at = 0; Settings:set("hardcover", a)
        T.eq(require("hardcover"):query("{ me { id } }"), nil)
        T.ok(require("hardcover"):isLinked(), "still linked")
    end)
    T.it("graphql errors come back as messages", function()
        local server = Fakes.hardcover()
        link(server)
        local Hardcover = require("hardcover")
        local post = Hardcover.post
        Hardcover.post = function(self, path, ...)
            if path == "/v1/graphql" then return 200, { errors = { { message = "field not found" } } } end
            return post(self, path, ...)
        end
        local data, err = Hardcover:query("{ nope }")
        T.eq(data, nil)
        T.eq(err, "field not found")
    end)
end)

T.describe("hardcover disconnect", function()
    T.it("revokes the refresh token on the server and forgets it", function()
        local server = Fakes.hardcover()
        link(server)
        require("hardcover"):unlink()
        T.eq(server.revoked, "hc_rt_1")
        T.ok(not require("hardcover"):isLinked())
    end)
    T.it("unlinking offline still forgets locally", function()
        local server = Fakes.hardcover()
        link(server)
        server.online = false
        require("hardcover"):unlink()
        T.ok(not require("hardcover"):isLinked())
    end)
    T.it("unlinking when not linked is harmless", function()
        Fakes.hardcover()
        require("hardcover"):unlink()
        T.ok(not require("hardcover"):isLinked())
    end)
end)

T.finish()
